#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
"""pi_mirror.py — mirror the HOST pi agent's model set into a sandbox.

Reads the host's own pi state (never writes it) and emits, on stdout, documents
that `just sbx lifecycle fill` pipes straight over ssh into the sandbox:

    models     the host's provider catalog + credentials, in pi's user-registry
               schema -> ~/.pi/agent/models.json on the VM
    settings   only the default provider/model/thinking level -> settings.json
    config     the active roster YAML with EVERY agent's model resolved against
               the host catalog -> /home/exedev/sssf_config.yaml

Stdout only, by design: the caller pipes each document over ssh, so a document
that holds secrets never lands in a temp file on either side.

SECURITY: `models` embeds the host's provider API keys (read from
~/.pi/agent/auth.json). Those keys cross to a disposable sandbox DELIBERATELY —
that is what lets the sandbox's pi call the host's real providers instead of the
OpenRouter fallback set. Treat this program's `models` output as secret: pipe it,
never print it back, never put it in argv.

Run it through uv (the PEP-723 header above has the pyyaml dependency):

    uv run sandbox_mount/host/pi_mirror.py models
    uv run sandbox_mount/host/pi_mirror.py settings
    uv run sandbox_mount/host/pi_mirror.py config --base adws/adw_sssf_config/sssf.config.yaml
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import NoReturn

import yaml

HOME = Path.home()
PI_AGENT = HOME / ".pi" / "agent"
MODELS_STORE = PI_AGENT / "models-store.json"
AUTH_FILE = PI_AGENT / "auth.json"
SETTINGS_FILE = PI_AGENT / "settings.json"

# The base roster when the caller does not name one; fill.just always passes the
# active `{{config}}` explicitly, so this is only the manual-invocation default.
DEFAULT_BASE = "adws/adw_sssf_config/sssf.config.yaml"

# ONLY the fields the proven `sandbox_mount/guest/models.json.tmpl` schema uses.
# pi's models.json is validated as a whole: an unknown/partial shape can make pi
# drop the entire roster, so this list is deliberately conservative.
_MODEL_FIELDS = ("id", "name", "contextWindow", "maxTokens", "reasoning", "input")
# ALL FOUR are required together — a partial cost block fails validation and pi
# then drops EVERY model, not just the one with the bad rates.
_COST_FIELDS = ("input", "output", "cacheRead", "cacheWrite")

_GENERATED_BANNER = (
    "# GENERATED by sandbox_mount/host/pi_mirror.py — DO NOT EDIT on the VM.\n"
    "# Edit the base roster (adws/adw_sssf_config/) and re-run FILL instead.\n"
    "# Every agent's model is resolved explicitly against the host pi catalog.\n"
)


def _fail(message: str, code: int = 1) -> NoReturn:
    print(f"pi_mirror: {message}", file=sys.stderr)
    sys.exit(code)


def _load_json(path: Path, label: str) -> dict:
    try:
        text = path.read_text()
    except FileNotFoundError:
        _fail(f"{label} not found at {path} — is the host pi agent configured?")
    except OSError as exc:
        _fail(f"cannot read {label} at {path}: {exc}")
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        _fail(f"{label} at {path} is not valid JSON: {exc}")
    if not isinstance(data, dict):
        _fail(f"{label} at {path} is not a JSON object")
    return data


def _providers(store: dict) -> dict:
    """Accept both the bare `{provider: {...}}` store and a `{"providers": ...}`
    wrapper, so a future pi cache-format change does not silently mirror nothing."""
    inner = store.get("providers")
    return inner if isinstance(inner, dict) else store


def _model_entry(model: dict) -> dict:
    entry: dict = {}
    for field in _MODEL_FIELDS:
        if field in model and model[field] is not None:
            entry[field] = model[field]
    entry.setdefault("id", model.get("id", ""))
    entry.setdefault("name", model.get("name") or entry["id"])
    cost = model.get("cost") or {}
    entry["cost"] = {field: cost.get(field, 0) for field in _COST_FIELDS}
    return entry


def cmd_models(args: argparse.Namespace) -> None:
    store = _load_json(MODELS_STORE, "host pi catalog (models-store.json)")
    auth = _load_json(AUTH_FILE, "host pi credentials (auth.json)")

    providers: dict = {}
    for name in sorted(_providers(store)):
        entry = _providers(store)[name]
        if not isinstance(entry, dict):
            continue
        models = [m for m in (entry.get("models") or []) if isinstance(m, dict)]
        if not models:
            continue

        credential = auth.get(name) or {}
        api_key = credential.get("key") if isinstance(credential, dict) else None
        if not api_key:
            # A keyless provider in the registry fails at call time anyway; skip
            # it loudly rather than shipping a provider that cannot authenticate.
            print(f"pi_mirror: skipping provider {name!r} — no api_key in auth.json",
                  file=sys.stderr)
            continue

        # baseUrl/api are uniform per provider on the host; take the first set.
        base_url = next((m.get("baseUrl") for m in models if m.get("baseUrl")), None)
        api = next((m.get("api") for m in models if m.get("api")), None)
        if not base_url or not api:
            print(f"pi_mirror: skipping provider {name!r} — its models carry no baseUrl/api",
                  file=sys.stderr)
            continue

        providers[name] = {
            "baseUrl": base_url,
            "api": api,
            "apiKey": api_key,
            "models": [_model_entry(m) for m in models],
        }

    if not providers:
        _fail("no host provider had both a catalog entry and a credential — "
              "cannot mirror the host model set")

    json.dump({"providers": providers}, sys.stdout, indent=2)
    sys.stdout.write("\n")


def cmd_settings(args: argparse.Namespace) -> None:
    settings = _load_json(SETTINGS_FILE, "host pi settings (settings.json)")
    # ONLY the defaults — host-only `packages`/extensions do not exist on the VM.
    out = {key: settings[key]
           for key in ("defaultProvider", "defaultModel", "defaultThinkingLevel")
           if key in settings}
    if "defaultProvider" not in out or "defaultModel" not in out:
        _fail("host settings.json has no defaultProvider/defaultModel to mirror")
    json.dump(out, sys.stdout, indent=2)
    sys.stdout.write("\n")


def _supported_models(store: dict) -> set[str]:
    supported: set[str] = set()
    for name, entry in _providers(store).items():
        if not isinstance(entry, dict):
            continue
        for model in entry.get("models") or []:
            if isinstance(model, dict) and model.get("id"):
                supported.add(f"{name}/{model['id']}")
    return supported


def _resolve(value, where: str, host_default: str | None, supported: set[str]) -> str:
    if value and value in supported:
        return value
    if value:
        print(f"pi_mirror: WARN {where}: model {value!r} is not in the host pi "
              f"catalog — substituting {host_default}", file=sys.stderr)
    else:
        print(f"pi_mirror: WARN {where}: no model configured — "
              f"substituting {host_default}", file=sys.stderr)
    if not host_default:
        _fail(f"{where}: no model configured and the host has no default model")
    return host_default


def cmd_config(args: argparse.Namespace) -> None:
    store = _load_json(MODELS_STORE, "host pi catalog (models-store.json)")
    settings = _load_json(SETTINGS_FILE, "host pi settings (settings.json)")

    supported = _supported_models(store)
    if not supported:
        _fail("host pi catalog is empty — nothing to validate the roster against")

    default_provider = settings.get("defaultProvider")
    default_model = settings.get("defaultModel")
    host_default = (f"{default_provider}/{default_model}"
                    if default_provider and default_model else None)
    if host_default:
        supported.add(host_default)

    base = Path(args.base)
    try:
        raw = base.read_text()
    except FileNotFoundError:
        _fail(f"base roster not found: {base}")
    except OSError as exc:
        _fail(f"cannot read base roster {base}: {exc}")
    try:
        data = yaml.safe_load(raw)
    except yaml.YAMLError as exc:
        _fail(f"base roster {base} is not valid YAML: {exc}")
    if not isinstance(data, dict):
        _fail(f"base roster {base} did not parse to a mapping")

    defaults = data.get("defaults")
    if not isinstance(defaults, dict):
        defaults = {}
        data["defaults"] = defaults
    defaults["model"] = _resolve(defaults.get("model"), "defaults", host_default, supported)

    # "Pre-filled": write the resolved value EXPLICITLY on every agent, so none
    # relies on inheritance in the generated file.
    for agent in data.get("agents") or []:
        if not isinstance(agent, dict):
            continue
        name = agent.get("name") or "?"
        agent["model"] = _resolve(agent.get("model"), f"agent {name}", host_default, supported)

    body = yaml.safe_dump(data, sort_keys=False, default_flow_style=False,
                          allow_unicode=True, width=4096)
    sys.stdout.write(_GENERATED_BANNER)
    sys.stdout.write(body)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        prog="pi_mirror.py",
        description="Mirror the host pi agent's model catalog/credentials into a sandbox.")
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("models", help="emit the host provider registry (with keys) as JSON")
    sub.add_parser("settings", help="emit the minimal host default settings as JSON")
    config = sub.add_parser("config", help="emit the roster with every model resolved")
    config.add_argument("--base", default=DEFAULT_BASE,
                        help=f"roster to resolve (default: {DEFAULT_BASE})")

    args = parser.parse_args(argv)
    {"models": cmd_models, "settings": cmd_settings, "config": cmd_config}[args.cmd](args)


if __name__ == "__main__":
    main()
